name: Run automated tests
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version: 24.14.1
          registry-url: https://registry.npmjs.org/
      - run: |
          npm ci
          npm run lint:ci
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version: 24.14.1
          registry-url: https://registry.npmjs.org/
      - run: |
          npm ci
          npm run test
  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version: 24.14.1
          registry-url: https://registry.npmjs.org/
      - run: |
          npm ci
          npm run tsc
